[tool.poetry]
name = "interval_generator"
version = "0.1.0"
description = "Generate images of musical intervals for importing to anki."
authors = ["Nicolas Schmitt <info@nicolaswebdev.com>"]

[tool.poetry.scripts]
start = "interval_generator.interval_generator:__main__"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
